name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Run tests
        run: ./gradlew test --stacktrace
